# Supporta NetGesCon

Se vuoi sostenere lo sviluppo di NetGesCon, puoi farlo tramite i seguenti canali:

- [PayPal](https://www.paypal.com/donate/?hosted_button_id=NPBKFSJCEVSLN)
- [Patreon](https://patreon.com/netgescon)

Grazie per il tuo supporto!

paypal: NPBKFSJCEVSLN
patreon: netgescon
custom: ["https://www.paypal.com/donate/?hosted_button_id=NPBKFSJCEVSLN", "https://patreon.com/netgescon"]
